---
title: "perception_gap_ingestion"
author: "Julia M.C."
date: "2026-04-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE}
# Loading the libraries and datasets
library(tidyverse)
library(lubridate)
setwd("~/Downloads/DATASETS")
crime <- read_csv("mc_crime.csv")
dispatch <- read_csv("mc_dispatch.csv")
bias <- read_csv("mc_bias_incidents.csv") 
citation <- read_csv("mc_citations.csv")
```

#CRIME
```{r}
head(crime)
unique(crime$"Police District Number")
```

```{r}
names(crime) <- tolower(names(crime)) 
names(crime) <- gsub(" ","_",names(crime))
head(crime)
```

```{r}
crime$start_date_time <- mdy_hms(crime$start_date_time)

crime$year <- year(crime$start_date_time)
crime$month <- month(crime$start_date_time)
crime$year_month <- floor_date(crime$start_date_time, "month")
```

```{r}
crime <- crime |>
  mutate(police_district_number = str_remove(police_district_number, "D"),police_district_number = str_trim(police_district_number))|>
  filter(police_district_number %in% c("1","2","3","4","5","6"))
```

#DISPATCH
```{r}
head(dispatch)
unique(dispatch$"Police District Number")
```

```{r}
names(dispatch) <- tolower(names(dispatch)) 
names(dispatch) <- gsub(" ","_",names(dispatch))
```

```{r}
dispatch$start_time <- mdy_hms(dispatch$start_time)

dispatch$year <- year(dispatch$start_time)
dispatch$month <- month(dispatch$start_time)
dispatch$year_month <- floor_date(dispatch$start_time, "month")
```

```{r}
dispatch <- dispatch|>
  mutate(police_district_number = as.character(police_district_number))
```

#BIAS
```{r}
head(bias)
unique(bias$"District")
```

```{r}
names(bias) <- tolower(names(bias)) 
names(bias) <- gsub(" ","_",names(bias))
```

```{r}
bias$incident_date <- as.Date(bias$incident_date, "%m/%d/%Y")

bias$year <- year(bias$incident_date)
bias$month <- month(bias$incident_date)
bias$year_month <- floor_date(bias$incident_date, "month")
```

```{r}
bias <- bias |>
  mutate(district = str_remove(district, "D"),district = str_trim(district))|>
  filter(district %in% c("1","2","3","4","5","6"))
```


# POLICE CRIMINAL CITATIONS
```{r}
head(citation)
unique(citation$"District")
```

```{r}
names(citation) <- tolower(names(citation)) 
names(citation) <- gsub(" ","_",names(citation))
names(citation) <- gsub("/","_",names(citation))
```

```{r}
citation$event_date_time <- parse_date_time(
  citation$event_date_time,
  orders = "Y b d I:M:S p"
)

citation$year <- year(citation$event_date_time)
citation$month <- month(citation$event_date_time)
citation$year_month <- floor_date(citation$event_date_time, "month")
```

```{r}
citation <- citation |>
  mutate(district = as.character(district)) |> 
  filter(district %in% c("1","2","3","4","5","6"))
```


```{r}
#write_csv(crime, "crime_cleaned.csv")
#write_csv(dispatch, "dispatch_cleaned.csv")
#write_csv(bias, "bias_cleaned.csv")
#write_csv(citation, "citation_cleaned.csv")
```

